"""Regenerate lp-cutoffs.js using the system libm (macOS / Linux, no packages).

LP_lm cutoffs: j_(l-1,m) for l >= 1; j_(1,m-1) for l = 0, m >= 2.
LP_01 has no cutoff. See the references in the calculator's formula panel.
"""

import ctypes
import ctypes.util
from pathlib import Path

MAX_V = 100
bessel = ctypes.CDLL(ctypes.util.find_library("m") or None).jn
bessel.argtypes = [ctypes.c_int, ctypes.c_double]
bessel.restype = ctypes.c_double

rows = []
for order in range(MAX_V):
    # J_n has no positive zeros at or below n; consecutive zeros are > pi apart.
    left = float(order)
    roots = []
    while left < MAX_V:
        right = min(left + 0.25, MAX_V)
        if bessel(order, left) * bessel(order, right) < 0:
            lo, hi = left, right
            for _ in range(48):
                mid = (lo + hi) / 2
                if bessel(order, lo) * bessel(order, mid) > 0:
                    lo = mid
                else:
                    hi = mid
            roots.append(f"{(lo + hi) / 2:.12f}")
        left = right
    if not roots:
        break
    rows.append("  [" + ", ".join(roots) + "],")

header = "// Generated by tools/generate-lp-cutoffs.py; positive zeros of J_n, row n.\n"
header += "// Complete for V <= 100. Values rounded to 12 decimal places.\n"
header += f"const LP_MAX_V = {MAX_V};\nconst LP_BESSEL_ZEROS = [\n"
Path(__file__).resolve().parents[1].joinpath("lp-cutoffs.js").write_text(
    header + "\n".join(rows) + "\n];\n", encoding="utf-8"
)
